#wallpaper {
#  monitor = 0
#  #path = /home/coldousedbird/Downloads/tentacles.jpg
#  path = /home/coldousedbird/Downloads/blyaa.jpg
#}
#

preload = /home/coldousedbird/pictures/tentacles.jpg
wallpaper = , /home/coldousedbird/pictures/tentacles.jpg
