[mgr]
ratio = [0, 4, 4]
sort_by = "alphabetical"
show_hidden = true
show_symlink = true
sort_dir_first = true
linemode = "file_info"
scrolloff = 7

# git plugin
# [[plugin.prepend_fetchers]]
# id   = "git"
# name = "*"
# run  = "git"
# [[plugin.prepend_fetchers]]
# id   = "git"
# name = "*/"
# run  = "git"


# [plugin]
# fetchers = [
# 	{ id = "current-size", name = "*/", run = "current-size", prio = "normal" },
# 	{ id = "current-size", name = "*", run = "current-size",prio = "normal" },
# ]
