set number
set relativenumber

set ignorecase
set showmatch
set hlsearch
set shiftwidth = 4
set tabstop = 4
set smartindent = true
" use system clipboard instead of local
clipboard = 'unnamedplus', -- 

expandtab = true,	         -- use spaces instead of tabs
tabstop = 2,               -- number of spaces for single <tab>
softtabstop = 2,           -- ?
shiftwidth = 2,            -- step of (auto)indent
smarttab = true,           -- autochoice number of spaces on <tab>
smartindent = true,        -- auto indentation on new lines

set incsearch
set ignorecase
incsearch = true,          -- show search matches as typing continues

termguicolors = true,      -- true color support ???
colorcolumn = '130',       -- highlight column
cursorline = true,         -- highlight current line

updatetime = 4000,         -- faster completion with 50 ms (default is 4000ms)

wildmenu = true,
wildmode = "longest:full,full",
splitright = true,

